# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ariasin/WorkJuice/rpg_project_source_code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ariasin/WorkJuice/rpg_project_source_code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariasin/WorkJuice/rpg_project_source_code/CMakeFiles /home/ariasin/WorkJuice/rpg_project_source_code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariasin/WorkJuice/rpg_project_source_code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpg_project

# Build rule for target.
rpg_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpg_project
.PHONY : rpg_project

# fast build rule for target.
rpg_project/fast:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/build
.PHONY : rpg_project/fast

src/critter.o: src/critter.cpp.o

.PHONY : src/critter.o

# target to build an object file
src/critter.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/critter.cpp.o
.PHONY : src/critter.cpp.o

src/critter.i: src/critter.cpp.i

.PHONY : src/critter.i

# target to preprocess a source file
src/critter.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/critter.cpp.i
.PHONY : src/critter.cpp.i

src/critter.s: src/critter.cpp.s

.PHONY : src/critter.s

# target to generate assembly for a file
src/critter.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/critter.cpp.s
.PHONY : src/critter.cpp.s

src/directory_reader.o: src/directory_reader.cpp.o

.PHONY : src/directory_reader.o

# target to build an object file
src/directory_reader.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/directory_reader.cpp.o
.PHONY : src/directory_reader.cpp.o

src/directory_reader.i: src/directory_reader.cpp.i

.PHONY : src/directory_reader.i

# target to preprocess a source file
src/directory_reader.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/directory_reader.cpp.i
.PHONY : src/directory_reader.cpp.i

src/directory_reader.s: src/directory_reader.cpp.s

.PHONY : src/directory_reader.s

# target to generate assembly for a file
src/directory_reader.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/directory_reader.cpp.s
.PHONY : src/directory_reader.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render_window.o: src/render_window.cpp.o

.PHONY : src/render_window.o

# target to build an object file
src/render_window.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/render_window.cpp.o
.PHONY : src/render_window.cpp.o

src/render_window.i: src/render_window.cpp.i

.PHONY : src/render_window.i

# target to preprocess a source file
src/render_window.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/render_window.cpp.i
.PHONY : src/render_window.cpp.i

src/render_window.s: src/render_window.cpp.s

.PHONY : src/render_window.s

# target to generate assembly for a file
src/render_window.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/render_window.cpp.s
.PHONY : src/render_window.cpp.s

src/roach.o: src/roach.cpp.o

.PHONY : src/roach.o

# target to build an object file
src/roach.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/roach.cpp.o
.PHONY : src/roach.cpp.o

src/roach.i: src/roach.cpp.i

.PHONY : src/roach.i

# target to preprocess a source file
src/roach.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/roach.cpp.i
.PHONY : src/roach.cpp.i

src/roach.s: src/roach.cpp.s

.PHONY : src/roach.s

# target to generate assembly for a file
src/roach.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/roach.cpp.s
.PHONY : src/roach.cpp.s

src/translator.o: src/translator.cpp.o

.PHONY : src/translator.o

# target to build an object file
src/translator.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/translator.cpp.o
.PHONY : src/translator.cpp.o

src/translator.i: src/translator.cpp.i

.PHONY : src/translator.i

# target to preprocess a source file
src/translator.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/translator.cpp.i
.PHONY : src/translator.cpp.i

src/translator.s: src/translator.cpp.s

.PHONY : src/translator.s

# target to generate assembly for a file
src/translator.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/translator.cpp.s
.PHONY : src/translator.cpp.s

src/world_builder.o: src/world_builder.cpp.o

.PHONY : src/world_builder.o

# target to build an object file
src/world_builder.cpp.o:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/world_builder.cpp.o
.PHONY : src/world_builder.cpp.o

src/world_builder.i: src/world_builder.cpp.i

.PHONY : src/world_builder.i

# target to preprocess a source file
src/world_builder.cpp.i:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/world_builder.cpp.i
.PHONY : src/world_builder.cpp.i

src/world_builder.s: src/world_builder.cpp.s

.PHONY : src/world_builder.s

# target to generate assembly for a file
src/world_builder.cpp.s:
	$(MAKE) -f CMakeFiles/rpg_project.dir/build.make CMakeFiles/rpg_project.dir/src/world_builder.cpp.s
.PHONY : src/world_builder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... rpg_project"
	@echo "... edit_cache"
	@echo "... src/critter.o"
	@echo "... src/critter.i"
	@echo "... src/critter.s"
	@echo "... src/directory_reader.o"
	@echo "... src/directory_reader.i"
	@echo "... src/directory_reader.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render_window.o"
	@echo "... src/render_window.i"
	@echo "... src/render_window.s"
	@echo "... src/roach.o"
	@echo "... src/roach.i"
	@echo "... src/roach.s"
	@echo "... src/translator.o"
	@echo "... src/translator.i"
	@echo "... src/translator.s"
	@echo "... src/world_builder.o"
	@echo "... src/world_builder.i"
	@echo "... src/world_builder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

